Patched a missing async/await, the dispatch returns a promise
goOHDARS/goDarsTest pull request #20
Opened 2024-05-22 21:09 UTC by ZacharyWolfe

In `src/unauthenticated/SignInScreen.tsx` **AND** `src/unauthenticated/AdditionalInfoScreen.tsx`
on lines 71 and 84 respectively.

The dispatch call returns a promise, which must be async/awaited

2024-05-22 21:12 UTC, ZacharyWolfe commented
I also changed the color of the spinning loader on the Button.tsx component. It looked rather off (blue loader on light green with white text) when making an account.

2024-05-23 03:24 UTC, Colinster327 requested changes
You do not need to await dispatches, you just can if you really need to.  For instance, when I dispatch signUpUser we still have the loading state which controls the loading and we don't need to promise resolution.  The two occurrences you mentioned do not need to be async at all.  On a side note, there is also no point to make a function async if the only thing that is called is the promise, aka there is nothing to await the resolution of the promise lol...

2024-05-26 13:29 UTC, Colinster327 approved these changes

2024-05-26 13:29 UTC, Reem-Lamsettef approved these changes

2024-05-26 13:36 UTC, merged